// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiH5kKqAQaG4m4ZFyX02qtyT3vKrnEIfw',
    appId: '1:1046274464042:web:e39747bf1f40e6ae7a2653',
    messagingSenderId: '1046274464042',
    projectId: 'mmlock-2d6a8',
    authDomain: 'mmlock-2d6a8.firebaseapp.com',
    storageBucket: 'mmlock-2d6a8.appspot.com',
    measurementId: 'G-303RGZ45N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz0-2hyjw5o09Nny1PiyISbuomVGfVC7s',
    appId: '1:1046274464042:android:e8275a1fce25d0867a2653',
    messagingSenderId: '1046274464042',
    projectId: 'mmlock-2d6a8',
    storageBucket: 'mmlock-2d6a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr00uxZLQmXMwi9sufDSDzUgeMiOLu8Y0',
    appId: '1:1046274464042:ios:e3feaffedeeafac87a2653',
    messagingSenderId: '1046274464042',
    projectId: 'mmlock-2d6a8',
    storageBucket: 'mmlock-2d6a8.appspot.com',
    iosClientId: '1046274464042-enqc94f1c7fm71a7g1q5lmsl84ka3vmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mmlock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr00uxZLQmXMwi9sufDSDzUgeMiOLu8Y0',
    appId: '1:1046274464042:ios:e3feaffedeeafac87a2653',
    messagingSenderId: '1046274464042',
    projectId: 'mmlock-2d6a8',
    storageBucket: 'mmlock-2d6a8.appspot.com',
    iosClientId: '1046274464042-enqc94f1c7fm71a7g1q5lmsl84ka3vmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mmlock',
  );
}
